### ISSUE TITLE
Clear out second parameter from `*path(char*,bool)`

### ISSUE THREAD

**Issue by no-lex** [project-imprimis/libprimis#100]
It doesn't do anything in the function itself, so references to it should be scrubbed.

**Comment by Duskhorn** [comment]
Upon further inspection, the `const` specifier didn't make any sense; thus I decided to modify parametars in function declarations to

**Comment by Duskhorn** [comment]
I'll merge the two functions together to a single `char *path(const char*)` then.
It's not a problem passing a `char*` parameter to a `const char*` right?

**Comment by no-lex** [comment]
```c++
template<size_t N>
inline char *copystring(char (&d)[N], const stringslice &s) { return copystring(d, s, N); }
```

**Comment by Duskhorn** [comment]
Do we really need those..?
If they are used all over the place then I'll keep using copystring
