### ISSUE TITLE
Misaligned equal signs in zip.cpp

### ISSUE THREAD

**Issue by nonoesimposible** [project-imprimis/libprimis#137]
https://github.com/project-imprimis/imprimis/blob/17eb9bc56cf668d8969a6bc3a3ecdacb4721d00f/src/shared/zip.cpp#L8-L16

The first two lines in this enum need another space so that all the equal signs line up with each other.

https://github.com/project-imprimis/imprimis/blob/master/doc/engine.md#112-cc-standards
> Enums also are always expanded with a single element per line. For aesthetics, it is best to place all the equals in the same location (as above). Imprimis uses no named enums besides those inhereted from ENet.

**Comment by azkoon** [comment]
#182
