### ISSUE TITLE
Replace `NULL` macro with `nullptr`

### ISSUE THREAD

**Issue by no-lex** [project-imprimis/libprimis#175]
The `NULL` formalism is no longer the canonical way to refer to the null pointer, as c++11 introduced the `nullptr` pointer literal.

### shared
- [x] shared/crypto
- [x] shared/geom
- [x] shared/glemu
- [x] shared/stream
- [x] shared/tools
- [x] shared/zip
### interface
- [x] engine/interface/command
- [x] engine/interface/console
- [x] engine/interface/control
- [x] engine/interface/cubestd
- [x] engine/interface/input
- [x] engine/interface/menus
- [x] engine/interface/sound
- [x] engine/interface/textedit
- [x] engine/interface/ui
### model
- [ ] engine/model/animmodel
- [x] engine/model/obj
- [ ] engine/model/ragdoll
- [ ] engine/model/skelmodel
### render
- [x] engine/render/aa
- [x] engine/render/ao
- [x] engine/render/csm
- [x] engine/render/grass
- [x] engine/render/hdr
- [x] engine/render/hud
- [x] engine/render/normal
- [x] engine/render/octarender
- [x] engine/render/radiancehints
- [x] engine/render/rendergl
- [x] engine/render/renderlights
- [x] engine/render/rendermodel
- [x] engine/render/renderparticles
- [x] engine/render/rendersky
- [x] engine/render/rendertext
- [x] engine/render/rendertimers
- [x] engine/render/renderva
- [x] engine/render/renderwindow
- [x] engine/render/shader
- [x] engine/render/stain
- [x] engine/render/texture
- [x] engine/render/water
### world
- [x] engine/world/bih
- [x] engine/world/dynlight
- [x] engine/world/light
- [x] engine/world/material
- [x] engine/world/mpr
- [x] engine/world/octa
- [x] engine/world/octaedit
- [x] engine/world/physics
- [x] engine/world/raycube
- [x] engine/world/world
- [x] engine/world/worldio

Also see: #132

**Comment by nonoesimposible** [comment]
yay
