### ISSUE TITLE
Rename `edgesortho` to be easier to understand

### ISSUE THREAD

**Issue by azkoon** [project-imprimis/libprimis#180]
`edgesortho` in `aa.cpp` is hard to decode at a first glance.

My suggestion would be either of:
- `edgeort`
- `edgeortho`
- `orthoedges`
to keep it concise and lowercase but improve readability.

**Comment by no-lex** [comment]
I think I prefer `orthoedges` over the other options. If you like, I can assign the issue to you (it should only be a few lines changed).

**Comment by azkoon** [comment]
Sure.
